In [2]:
import numpy as np
np.__version__

'1.21.2'

In [3]:
import pandas as pd
pd.__version__

'1.3.2'

In [4]:
df = pd.read_csv("data.csv")

In [5]:
df[df['Make'] == 'BMW'].mean()

/tmp/ipykernel_56/406413765.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df[df['Make'] == 'BMW'].mean()


Year                 2014.347305
Engine HP             326.907186
Engine Cylinders        5.958084
Number of Doors         3.161677
highway MPG            29.245509
city mpg               20.739521
Popularity           3916.000000
MSRP                61546.763473
dtype: float64

In [6]:
df[(df['Year'] >= 2015) & (df['Engine HP'].isnull() == True)].count()

Make                 51
Model                51
Year                 51
Engine Fuel Type     51
Engine HP             0
Engine Cylinders     51
Transmission Type    51
Driven_Wheels        51
Number of Doors      46
Market Category      46
Vehicle Size         51
Vehicle Style        51
highway MPG          51
city mpg             51
Popularity           51
MSRP                 51
dtype: int64

In [7]:
round(df['Engine HP'].mean())

249

In [8]:
round(df['Engine HP'].fillna(df['Engine HP'].mean()).mean())

249

In [93]:
X = (df[df['Make'] == 'Rolls-Royce'])[['Engine HP','Engine Cylinders','highway MPG']].drop_duplicates().values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [97]:
XT = X.T
XT
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [98]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [99]:
XTXinv.sum()

0.032212320677486125

In [79]:
y = np.array([[1000, 1100, 900, 1200, 1000, 850, 1300]])
y

array([[1000, 1100,  900, 1200, 1000,  850, 1300]])

In [100]:
XTXinvXT = XTXinv.dot(X.T)
XTXinvXT

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [105]:
w = XTXinvXT * (y)
w[0]

array([-4.86592076,  3.70158161, -0.44514862,  1.72227877, -1.39491731,
       -1.98126399,  3.46328627])